In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(color_codes=True)

In [2]:
df = pd.read_csv("data.csv")
# To display the top 5 rows
df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [3]:
df = df.drop(['Engine Fuel Type', 'Market Category', 'Vehicle Style', 'Popularity', 'Number of Doors', 'Vehicle Size'], axis=1)
df.head(5)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500

In [6]:
df['Transmission Type'].value_counts()

AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: Transmission Type, dtype: int64

In [16]:
one_hot = pd.get_dummies(df['Transmission Type']).reset_index()

In [24]:
df2 = df.reset_index()

In [25]:
one_hot

       index  AUTOMATED_MANUAL  AUTOMATIC  DIRECT_DRIVE  MANUAL  UNKNOWN
0          0                 0          0             0       1        0
1          1                 0          0             0       1        0
2          2                 0          0             0       1        0
3          3                 0          0             0       1        0
4          4                 0          0             0       1        0
...      ...               ...        ...           ...     ...      ...
11909  11909                 0          1             0       0        0
11910  11910                 0          1             0       0        0
11911  11911                 0          1             0       0        0
11912  11912                 0          1             0       0        0
11913  11913                 0          1             0       0        0

[11914 rows x 6 columns]

In [26]:
df2 = pd.merge(one_hot, df2, on='index')

In [27]:
df2

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,0,1,0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,1,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,2,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,3,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,4,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,11910,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,11911,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,11912,0,1,0,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,11913,0,1,0,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [28]:
df2.drop(columns='index')

,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,1,0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,0,1,0,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,0,1,0,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [33]:
df_filter = df2[df2['UNKNOWN'] != 1]

In [34]:
df_filter

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,0,1,0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,1,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,2,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,3,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,4,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,11910,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,11911,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,11912,0,1,0,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,11913,0,1,0,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [36]:
final_df = df_filter.drop(columns=['UNKNOWN', 'index'])

In [37]:
final_df

,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,1,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,0,0,0,1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,0,0,0,1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,0,0,0,1,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,0,0,0,1,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,0,1,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,0,1,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,0,1,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,0,1,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,0,1,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [69]:
# look up inplace
df2 = df2.fillna(method='ffill')

In [70]:
# independent variable
X = df2[{'MANUAL', 'DIRECT_DRIVE', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'Engine HP'}]
# target variable
y = df2['MSRP']

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, 
                                                    test_size = 0.2)

In [72]:
import statsmodels.api as sm

# Adding a constant to get an intercept
X_train_sm = sm.add_constant(X_train)

In [73]:
# Fitting the resgression line using 'OLS'
# ordinary lease squares
lr = sm.OLS(y_train, X_train_sm).fit()

# Printing the parameters
lr.params

const              -61162.995453
MANUAL              11055.040728
DIRECT_DRIVE        31931.842157
AUTOMATIC            7173.478850
Engine HP             368.849380
AUTOMATED_MANUAL    45227.639624
dtype: float64

In [74]:
lr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MSRP   R-squared:                       0.444
Model:                            OLS   Adj. R-squared:                  0.444
Method:                 Least Squares   F-statistic:                     1522.
Date:                Thu, 26 Aug 2021   Prob (F-statistic):               0.00
Time:                        09:44:05   Log-Likelihood:            -1.1611e+05
No. Observations:                9531   AIC:                         2.322e+05
Df Residuals:                    9525   BIC:                         2.323e+05
Df Model:                           5
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const            -6.116e+04   1.37e+04     -4.476      0.000    -8.8e+04   -3.44e+04
MANUAL            1.106e+04   1.37e+04      0.808      0.419   -1.58e+04    3.79e+04
DIRECT_DRIVE      3.193e+04    1.5e+04      2.134      0.033    2595.303    6.13e+04
AUTOMATIC         7173.4788   1.37e+04      0.525      0.599   -1.96e+04    3.39e+04
Engine HP          368.8494      4.570     80.717      0.000     359.892     377.807
AUTOMATED_MANUAL  4.523e+04   1.38e+04      3.272      0.001    1.81e+04    7.23e+04
==============================================================================
Omnibus:                    18866.875   Durbin-Watson:                   1.980
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         76824879.777
Skew:                          15.748   Prob(JB):                         0.00
Kurtosis:                     441.703   Cond. No.                     1.73e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
# this data needs to be normalized
# this data needs to remove outliers