In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(color_codes=True)

In [2]:
df = pd.read_csv("data.csv")
# To display the top 5 rows
df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [3]:
df = df.drop(['Engine Fuel Type', 'Market Category', 'Vehicle Style', 'Popularity', 'Number of Doors', 'Vehicle Size'], axis=1)
df.head(5)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500

In [6]:
df['Transmission Type'].value_counts()

AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: Transmission Type, dtype: int64

In [16]:
one_hot = pd.get_dummies(df['Transmission Type']).reset_index()

In [24]:
df2 = df.reset_index()

In [25]:
one_hot

       index  AUTOMATED_MANUAL  AUTOMATIC  DIRECT_DRIVE  MANUAL  UNKNOWN
0          0                 0          0             0       1        0
1          1                 0          0             0       1        0
2          2                 0          0             0       1        0
3          3                 0          0             0       1        0
4          4                 0          0             0       1        0
...      ...               ...        ...           ...     ...      ...
11909  11909                 0          1             0       0        0
11910  11910                 0          1             0       0        0
11911  11911                 0          1             0       0        0
11912  11912                 0          1             0       0        0
11913  11913                 0          1             0       0        0

[11914 rows x 6 columns]

In [26]:
df2 = pd.merge(one_hot, df2, on='index')

In [27]:
df2

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,0,1,0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,1,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,2,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,3,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,4,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,11910,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,11911,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,11912,0,1,0,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,11913,0,1,0,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [28]:
df2.drop(columns='index')

,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,1,0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,0,1,0,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,0,1,0,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [33]:
df_filter = df2[df2['UNKNOWN'] != 1]

In [34]:
df_filter

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,0,1,0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,1,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,2,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,3,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,4,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,11910,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,11911,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,11912,0,1,0,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,11913,0,1,0,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [36]:
final_df = df_filter.drop(columns=['UNKNOWN', 'index'])

In [37]:
final_df

,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,1,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,0,0,0,1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,0,0,0,1,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,0,0,0,1,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,0,0,0,1,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,0,1,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,0,1,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,0,1,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,0,1,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,0,1,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [69]:
# look up inplace
df2 = df2.fillna(method='ffill')

In [70]:
# independent variable
X = df2[{'MANUAL', 'DIRECT_DRIVE', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'Engine HP'}]
# target variable
y = df2['MSRP']

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, 
                                                    test_size = 0.2)

In [72]:
import statsmodels.api as sm

# Adding a constant to get an intercept
X_train_sm = sm.add_constant(X_train)

In [73]:
# Fitting the resgression line using 'OLS'
# ordinary lease squares
lr = sm.OLS(y_train, X_train_sm).fit()

# Printing the parameters
lr.params

const              -61162.995453
MANUAL              11055.040728
DIRECT_DRIVE        31931.842157
AUTOMATIC            7173.478850
Engine HP             368.849380
AUTOMATED_MANUAL    45227.639624
dtype: float64

In [74]:
lr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MSRP   R-squared:                       0.444
Model:                            OLS   Adj. R-squared:                  0.444
Method:                 Least Squares   F-statistic:                     1522.
Date:                Thu, 26 Aug 2021   Prob (F-statistic):               0.00
Time:                        09:44:05   Log-Likelihood:            -1.1611e+05
No. Observations:                9531   AIC:                         2.322e+05
Df Residuals:                    9525   BIC:                         2.323e+05
Df Model:                           5
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const            -6.116e+04   1.37e+04     -4.476      0.000    -8.8e+04   -3.44e+04
MANUAL            1.106e+04   1.37e+04      0.808      0.419   -1.58e+04    3.79e+04
DIRECT_DRIVE      3.193e+04    1.5e+04      2.134      0.033    2595.303    6.13e+04
AUTOMATIC         7173.4788   1.37e+04      0.525      0.599   -1.96e+04    3.39e+04
Engine HP          368.8494      4.570     80.717      0.000     359.892     377.807
AUTOMATED_MANUAL  4.523e+04   1.38e+04      3.272      0.001    1.81e+04    7.23e+04
==============================================================================
Omnibus:                    18866.875   Durbin-Watson:                   1.980
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         76824879.777
Skew:                          15.748   Prob(JB):                         0.00
Kurtosis:                     441.703   Cond. No.                     1.73e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
# this data needs to be normalized
# this data needs to remove outliers

In [75]:
df3 = df2[(df['MSRP'] < 100000) & (df['Engine HP'] < 450)]

In [76]:
df3

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,highway MPG,city mpg,MSRP
0,0,0,0,0,1,0,BMW,1 Series M,2011,335.0,6.0,MANUAL,rear wheel drive,26,19,46135
1,1,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,19,40650
2,2,0,0,0,1,0,BMW,1 Series,2011,300.0,6.0,MANUAL,rear wheel drive,28,20,36350
3,3,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,29450
4,4,0,0,0,1,0,BMW,1 Series,2011,230.0,6.0,MANUAL,rear wheel drive,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11909,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,46120
11910,11910,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,56670
11911,11911,0,1,0,0,0,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50620
11912,11912,0,1,0,0,0,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,all wheel drive,23,16,50920
11913,11913,0,1,0,0,0,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,front wheel drive,26,17,28995

In [77]:
# independent variable
X = df3[{'MANUAL', 'DIRECT_DRIVE', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'Engine HP', 'highway MPG', 'Year'}]
# target variable
y = df3['MSRP']

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, 
                                                    test_size = 0.2)

In [106]:
import statsmodels.api as sm

# Adding a constant to get an intercept
X_train_sm = sm.add_constant(X_train)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [107]:
# Fitting the resgression line using 'OLS'
# ordinary lease squares
lr = sm.OLS(y_train, X_train_sm).fit()

# Printing the parameters
lr.params

const              -1.648016e+06
Year                8.140169e+02
MANUAL              2.983618e+03
DIRECT_DRIVE        4.385967e+03
highway MPG         1.682600e+02
AUTOMATIC           4.944218e+03
Engine HP           1.412269e+02
AUTOMATED_MANUAL    8.222579e+03
dtype: float64

In [108]:
lr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MSRP   R-squared:                       0.714
Model:                            OLS   Adj. R-squared:                  0.714
Method:                 Least Squares   F-statistic:                     3137.
Date:                Thu, 26 Aug 2021   Prob (F-statistic):               0.00
Time:                        09:49:43   Log-Likelihood:                -93246.
No. Observations:                8812   AIC:                         1.865e+05
Df Residuals:                    8804   BIC:                         1.866e+05
Df Model:                           7
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const            -1.648e+06   3.54e+04    -46.507      0.000   -1.72e+06   -1.58e+06
Year               814.0169     17.898     45.481      0.000     778.933     849.101
MANUAL            2983.6184   2398.908      1.244      0.214   -1718.801    7686.038
DIRECT_DRIVE      4385.9668   3457.575      1.269      0.205   -2391.688    1.12e+04
highway MPG        168.2600     18.524      9.083      0.000     131.949     204.571
AUTOMATIC         4944.2179   2400.144      2.060      0.039     239.375    9649.061
Engine HP          141.2269      1.736     81.360      0.000     137.824     144.630
AUTOMATED_MANUAL  8222.5787   2457.769      3.346      0.001    3404.778     1.3e+04
==============================================================================
Omnibus:                     1732.561   Durbin-Watson:                   2.022
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6057.588
Skew:                           0.970   Prob(JB):                         0.00
Kurtosis:                       6.568   Cond. No.                     7.06e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.06e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [109]:
normalized_data = df3.values

In [110]:
normalized_data

array([[0, 0, 0, ..., 26, 19, 46135],
       [1, 0, 0, ..., 28, 19, 40650],
       [2, 0, 0, ..., 28, 20, 36350],
       ...,
       [11911, 0, 1, ..., 23, 16, 50620],
       [11912, 0, 1, ..., 23, 16, 50920],
       [11913, 0, 1, ..., 26, 17, 28995]], dtype=object)

In [111]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
EX_scaled = min_max_scaler.fit_transform(normalized_data)

ValueError: could not convert string to float: 'BMW'

In [113]:
df4 = df3.drop(['Make', 'Model', 'Driven_Wheels', 'Transmission Type'], axis=1)
df4.head(5)

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Year,Engine HP,Engine Cylinders,highway MPG,city mpg,MSRP
0,0,0,0,0,1,0,2011,335.0,6.0,26,19,46135
1,1,0,0,0,1,0,2011,300.0,6.0,28,19,40650
2,2,0,0,0,1,0,2011,300.0,6.0,28,20,36350
3,3,0,0,0,1,0,2011,230.0,6.0,28,18,29450
4,4,0,0,0,1,0,2011,230.0,6.0,28,18,34500

In [125]:
df4 = df3.drop(['Make', 'Model', 'Driven_Wheels', 'Transmission Type'], axis=1)

In [126]:
normalized_data = df4.values

In [127]:
normalized_data

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.6000e+01, 1.9000e+01,
        4.6135e+04],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.8000e+01, 1.9000e+01,
        4.0650e+04],
       [2.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.8000e+01, 2.0000e+01,
        3.6350e+04],
       ...,
       [1.1911e+04, 0.0000e+00, 1.0000e+00, ..., 2.3000e+01, 1.6000e+01,
        5.0620e+04],
       [1.1912e+04, 0.0000e+00, 1.0000e+00, ..., 2.3000e+01, 1.6000e+01,
        5.0920e+04],
       [1.1913e+04, 0.0000e+00, 1.0000e+00, ..., 2.6000e+01, 1.7000e+01,
        2.8995e+04]])

In [132]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
normalized_data = min_max_scaler.fit_transform(normalized_data)

In [133]:
normalized_data

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.09356725e-02, 7.08661417e-02, 4.50817160e-01],
       [8.39419122e-05, 0.00000000e+00, 0.00000000e+00, ...,
        4.67836257e-02, 7.08661417e-02, 3.94790603e-01],
       [1.67883824e-04, 0.00000000e+00, 0.00000000e+00, ...,
        4.67836257e-02, 7.87401575e-02, 3.50868233e-01],
       ...,
       [9.99832116e-01, 0.00000000e+00, 1.00000000e+00, ...,
        3.21637427e-02, 4.72440945e-02, 4.96629213e-01],
       [9.99916058e-01, 0.00000000e+00, 1.00000000e+00, ...,
        3.21637427e-02, 4.72440945e-02, 4.99693565e-01],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        4.09356725e-02, 5.51181102e-02, 2.75740552e-01]])

In [134]:
normalized_data = pd.DataFrame(normalized_data, columns = df4.columns, index=df4.index)

In [135]:
normalized_data

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Year,Engine HP,Engine Cylinders,highway MPG,city mpg,MSRP
0,0.000000,0.0,0.0,0.0,1.0,0.0,0.777778,0.710660,0.5,0.040936,0.070866,0.450817
1,0.000084,0.0,0.0,0.0,1.0,0.0,0.777778,0.621827,0.5,0.046784,0.070866,0.394791
2,0.000168,0.0,0.0,0.0,1.0,0.0,0.777778,0.621827,0.5,0.046784,0.078740,0.350868
3,0.000252,0.0,0.0,0.0,1.0,0.0,0.777778,0.444162,0.5,0.046784,0.062992,0.280388
4,0.000336,0.0,0.0,0.0,1.0,0.0,0.777778,0.444162,0.5,0.046784,0.062992,0.331971
...,...,...,...,...,...,...,...,...,...,...,...,...
11909,0.999664,0.0,1.0,0.0,0.0,0.0,0.814815,0.621827,0.5,0.032164,0.047244,0.450664
11910,0.999748,0.0,1.0,0.0,0.0,0.0,0.814815,0.621827,0.5,0.032164,0.047244,0.558427
11911,0.999832,0.0,1.0,0.0,0.0,0.0,0.814815,0.621827,0.5,0.032164,0.047244,0.496629
11912,0.999916,0.0,1.0,0.0,0.0,0.0,0.851852,0.621827,0.5,0.032164,0.047244,0.499694
11913,1.000000,0.0,1.0,0.0,0.0,0.0,0.592593,0.421320,0.5,0.040936,0.055118,0.275741

In [148]:
X = normalized_data[{'MANUAL', 'DIRECT_DRIVE', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'Engine HP', 'highway MPG', 'Year'}]
# target variable
y = normalized_data['MSRP']

In [149]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, 
                                                    test_size = 0.2)

In [150]:
import statsmodels.api as sm

# Adding a constant to get an intercept
X_train_sm = sm.add_constant(X_train)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [151]:
# Fitting the resgression line using 'OLS'
# ordinary lease squares
lr = sm.OLS(y_train, X_train_sm).fit()

# Printing the parameters
lr.params

const              -0.199617
Year                0.227907
MANUAL              0.021287
DIRECT_DRIVE        0.026757
highway MPG         0.588419
AUTOMATIC           0.039359
Engine HP           0.568084
AUTOMATED_MANUAL    0.074329
dtype: float64

In [152]:
lr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MSRP   R-squared:                       0.711
Model:                            OLS   Adj. R-squared:                  0.711
Method:                 Least Squares   F-statistic:                     3102.
Date:                Thu, 26 Aug 2021   Prob (F-statistic):               0.00
Time:                        10:08:09   Log-Likelihood:                 7952.2
No. Observations:                8812   AIC:                        -1.589e+04
Df Residuals:                    8804   BIC:                        -1.583e+04
Df Model:                           7
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -0.1996      0.026     -7.568      0.000      -0.251      -0.148
Year                 0.2279      0.005     46.148      0.000       0.218       0.238
MANUAL               0.0213      0.026      0.807      0.420      -0.030       0.073
DIRECT_DRIVE         0.0268      0.038      0.710      0.478      -0.047       0.101
highway MPG          0.5884      0.065      9.007      0.000       0.460       0.716
AUTOMATIC            0.0394      0.026      1.491      0.136      -0.012       0.091
Engine HP            0.5681      0.007     80.690      0.000       0.554       0.582
AUTOMATED_MANUAL     0.0743      0.027      2.757      0.006       0.021       0.127
==============================================================================
Omnibus:                     1868.515   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6753.768
Skew:                           1.035   Prob(JB):                         0.00
Kurtosis:                       6.756   Cond. No.                         101.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [142]:
normalized_data

,index,AUTOMATED_MANUAL,AUTOMATIC,DIRECT_DRIVE,MANUAL,UNKNOWN,Year,Engine HP,Engine Cylinders,highway MPG,city mpg,MSRP
0,0.000000,0.0,0.0,0.0,1.0,0.0,0.777778,0.710660,0.5,0.040936,0.070866,0.450817
1,0.000084,0.0,0.0,0.0,1.0,0.0,0.777778,0.621827,0.5,0.046784,0.070866,0.394791
2,0.000168,0.0,0.0,0.0,1.0,0.0,0.777778,0.621827,0.5,0.046784,0.078740,0.350868
3,0.000252,0.0,0.0,0.0,1.0,0.0,0.777778,0.444162,0.5,0.046784,0.062992,0.280388
4,0.000336,0.0,0.0,0.0,1.0,0.0,0.777778,0.444162,0.5,0.046784,0.062992,0.331971
...,...,...,...,...,...,...,...,...,...,...,...,...
11909,0.999664,0.0,1.0,0.0,0.0,0.0,0.814815,0.621827,0.5,0.032164,0.047244,0.450664
11910,0.999748,0.0,1.0,0.0,0.0,0.0,0.814815,0.621827,0.5,0.032164,0.047244,0.558427
11911,0.999832,0.0,1.0,0.0,0.0,0.0,0.814815,0.621827,0.5,0.032164,0.047244,0.496629
11912,0.999916,0.0,1.0,0.0,0.0,0.0,0.851852,0.621827,0.5,0.032164,0.047244,0.499694
11913,1.000000,0.0,1.0,0.0,0.0,0.0,0.592593,0.421320,0.5,0.040936,0.055118,0.275741

In [ ]:
# normalizing didn't help at all
# maybe normalizing al columns is bad?